### ISSUE TITLE
Broken `yarn scripts docs.dev` script

### ISSUE THREAD

**Issue by landitus** [auth0/cosmos#643]
I believe this only happens on my machine, but when I run `yarns scripts docs.dev` I get the following errors:

```
[docs.dev_site] ℹ ｢hot｣: webpack: Compiling...
[docs.dev_site] ✖ ｢hot｣: WebSocket Server Error { Error: getaddrinfo ENOTFOUND localhost
[docs.dev_site]     at errnoException (dns.js:50:10)
[docs.dev_site]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
[docs.dev_site]   code: 'ENOTFOUND',
[docs.dev_site]   errno: 'ENOTFOUND',
[docs.dev_site]   syscall: 'getaddrinfo',
[docs.dev_site]   hostname: 'localhost' }
[docs.dev_site] ✖ ｢serve｣:  { Error: getaddrinfo ENOTFOUND localhost
[docs.dev_site]     at errnoException (dns.js:50:10)
[docs.dev_site]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
[docs.dev_site]   code: 'ENOTFOUND',
[docs.dev_site]   errno: 'ENOTFOUND',
[docs.dev_site]   syscall: 'getaddrinfo',
[docs.dev_site]   hostname: 'localhost' }
```
The script ends in 
```
[docs.dev_site] ℹ ｢wdm｣: Compiled successfully.
```
but the server doesn't work 😓

**Comment by siddharthkp** [comment]
@francocorreasosa @nkohari @beneliflo Does this happen to you as well?

I couldn't reproduce this on my machine and searching the error messages didn't lead to anything useful 😢

**Comment by francocorreasosa** [comment]
Mine is working fine. Maybe a fresh `yarn` is necessary?

**Comment by francocorreasosa** [comment]
Can you try deleting `node_modules` and reinstalling the modules? Actually that's what I meant in my previous comment, sorry for the confusion 😅

**Comment by landitus** [comment]
Done and same happens

**Comment by landitus** [comment]
Sorry, it was my setup! Closing it!
